# Generated by Django 4.2.25 on 2025-11-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp33", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="birthday",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="email",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="profession",
        ),
        migrations.AddField(
            model_name="contact",
            name="city",
            field=models.CharField(default="Beirut", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="fees",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="hospital",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="rating",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="specialty",
            field=models.CharField(default="General", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
