# Generated by Django 4.2.25 on 2025-11-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp33", "0002_remove_contact_birthday_remove_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="availability",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="contact",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="contact",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="experience_years",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="contact",
            name="insurance_partners",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="contact",
            name="languages",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="contact",
            name="photo_url",
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name="AppointmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=120)),
                ("patient_email", models.EmailField(max_length=254)),
                ("patient_phone", models.CharField(blank=True, max_length=30)),
                ("preferred_date", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="myapp33.contact",
                    ),
                ),
            ],
        ),
    ]
